:headline: Curriculum Vitae
:body: |
  <p>You can download my CV <a href="cv_logacev.pdf">here</a> or browse it below.</p>	 
  <object data="cv_logacev.pdf" type="application/pdf" width="100%" height="400px"></object>
